//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_mycontrols : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.mycontrols_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.mycontrols_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadPress
        {
            get
            {
                return SteamVR_Actions.mycontrols_TrackpadPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadTouch
        {
            get
            {
                return SteamVR_Actions.mycontrols_TrackpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.mycontrols_Menu;
            }
        }
        
        public virtual SteamVR_Action_Single PressPinch
        {
            get
            {
                return SteamVR_Actions.mycontrols_PressPinch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TrackpadDirection
        {
            get
            {
                return SteamVR_Actions.mycontrols_TrackpadDirection;
            }
        }
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.mycontrols_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.mycontrols_Haptic;
            }
        }
    }
}
